class NameChar {
  final String char;
  final String pinyin;
  final List<String> meanings;
  final String element;
  final String emoji;
  final String notes;
  NameChar(this.char, this.pinyin, this.meanings, this.element, this.emoji, this.notes);
}

final Map<String, NameChar> nameDict = {
  '伟': NameChar('伟', 'wěi', ['Great', 'Mighty', 'Grand'], '土', '✨', 'Popular name character for boys.'),
  '强': NameChar('强', 'qiáng', ['Strong', 'Powerful', 'Superior'], '金', '💪', 'Inner strength and resilience.'),
  '明': NameChar('明', 'míng', ['Bright', 'Clear', 'Intelligent'], '火', '💡', 'Sun+moon radicals. Very popular.'),
  '慧': NameChar('慧', 'huì', ['Wise', 'Intelligent', 'Bright'], '水', '🦉', 'Keen intelligence and wisdom.'),
  '琳': NameChar('琳', 'lín', ['Jade', 'Gem', 'Beautiful'], '木', '💎', 'Beautiful jade. Precious stone.'),
  '雅': NameChar('雅', 'yǎ', ['Elegant', 'Refined', 'Graceful'], '木', '🎵', 'Elegance and sophistication.'),
  '婷': NameChar('婷', 'tíng', ['Graceful', 'Elegant', 'Slender'], '木', '💃', 'Graceful, elegant posture.'),
  '志': NameChar('志', 'zhì', ['Ambition', 'Will', 'Aspiration'], '火', '🎯', 'Ambition and willpower.'),
  '龙': NameChar('龙', 'lóng', ['Dragon', 'Powerful', 'Noble'], '水', '🐉', 'Imperial dragon. Supreme power.'),
  '美': NameChar('美', 'měi', ['Beautiful', 'Pretty', 'Elegant'], '水', '🌸', 'The character for beauty itself.'),
  '丽': NameChar('丽', 'lì', ['Beautiful', 'Lovely', 'Graceful'], '火', '💐', 'Loveliness and grace.'),
  '娜': NameChar('娜', 'nà', ['Elegant', 'Graceful', 'Charming'], '水', '✨', 'Elegance and charm.'),
  '杰': NameChar('杰', 'jié', ['Outstanding', 'Heroic', 'Eminent'], '木', '🌟', 'Outstanding or heroic.'),
  '文': NameChar('文', 'wén', ['Literary', 'Culture', 'Elegant'], '水', '📖', 'Culture and refinement.'),
  '博': NameChar('博', 'bó', ['Broad', 'Erudite', 'Wealthy'], '水', '🌐', 'Broad learning and erudition.'),
  '睿': NameChar('睿', 'ruì', ['Astute', 'Perceptive', 'Wise'], '金', '🔮', 'Deep wisdom and farsightedness.'),
  '英': NameChar('英', 'yīng', ['Heroic', 'Outstanding', 'Brave'], '木', '🏆', 'Heroic and outstanding.'),
  '勇': NameChar('勇', 'yǒng', ['Brave', 'Courageous', 'Valiant'], '火', '🦁', 'Emboldies courage and bravery.'),
  '毅': NameChar('毅', 'yì', ['Firm', 'Persevering', 'Resolute'], '木', '🎯', 'Determination and willpower.'),
  '健': NameChar('健', 'jiàn', ['Healthy', 'Strong', 'Robust'], '木', '🏋️', 'Health and strength combined.'),
  '海': NameChar('海', 'hǎi', ['Ocean', 'Sea', 'Vast'], '水', '🌊', 'The ocean. Very popular.'),
  '天': NameChar('天', 'tiān', ['Heaven', 'Sky', 'Supreme'], '火', '🌌', 'Heaven and sky.'),
  '秀': NameChar('秀', 'xiù', ['Elegant', 'Graceful', 'Outstanding'], '木', '🌿', 'Elegant refinement.'),
  '张': NameChar('张', 'zhāng', ['Open', 'Spread', 'Archer'], '火', '🏮', 'Common surname.'),
  '李': NameChar('李', 'lǐ', ['Plum', 'Justice'], '木', '🌸', 'Most common surname.'),
  '王': NameChar('王', 'wáng', ['King', 'Royal'], '土', '👑', 'Common surname.'),
  '赵': NameChar('赵', 'zhào', ['Zhao', 'Rapid'], '火', '🚀', 'Common surname.'),
  '刘': NameChar('刘', 'liú', ['Kill', 'Flow'], '金', '🌊', 'Common surname.'),
  '陈': NameChar('陈', 'chén', ['Exhibit', 'Old'], '火', '🏛️', 'Common surname.'),
  '杨': NameChar('杨', 'yáng', ['Poplar', 'Aspire'], '木', '🌳', 'Common surname.'),
  '黄': NameChar('黄', 'huáng', ['Yellow', 'Gold'], '土', '💛', 'Common surname.'),
  '周': NameChar('周', 'zhōu', ['Circle', 'Cycle'], '土', '🔄', 'Common surname.'),
  '吴': NameChar('吴', 'wú', ['Wu', 'Grand'], '水', '🗣️', 'Common surname.'),
  '徐': NameChar('徐', 'xú', ['Slow', 'Gentle'], '金', '🐢', 'Common surname.'),
  '孙': NameChar('孙', 'sūn', ['Grandson', 'Descendant'], '水', '👶', 'Common surname.'),
  '马': NameChar('马', 'mǎ', ['Horse', 'Gallant'], '火', '🐎', 'Common surname.'),
  '朱': NameChar('朱', 'zhū', ['Vermilion', 'Red'], '火', '🔴', 'Common surname.'),
  '胡': NameChar('胡', 'hú', ['Barbarian', 'Wild'], '土', '🧔', 'Common surname.'),
  '林': NameChar('林', 'lín', ['Forest'], '木', '🌲', 'Common surname.'),
  '高': NameChar('高', 'gāo', ['Tall', 'Superior'], '木', '📈', 'Common surname.'),
  '瑞': NameChar('瑞', 'ruì', ['Auspicious', 'Lucky'], '金', '🍀', 'Auspicious omens.'),
  '祥': NameChar('祥', 'xiáng', ['Auspicious', 'Blessed'], '金', '✨', 'Auspiciousness.'),
  '福': NameChar('福', 'fú', ['Fortune', 'Blessing'], '水', '🧧', 'Fortune itself.'),
  '金': NameChar('金', 'jīn', ['Gold', 'Metal'], '金', '🥇', 'Gold and precious metals.'),
  '玉': NameChar('玉', 'yù', ['Jade', 'Pure'], '土', '💚', 'Pure jade.'),
  '宝': NameChar('宝', 'bǎo', ['Treasure', 'Precious'], '火', '💎', 'Treasure.'),
  '华': NameChar('华', 'huá', ['Splendid', 'Magnificent'], '水', '🌺', 'Splendor.'),
  '富': NameChar('富', 'fù', ['Rich', 'Wealthy'], '水', '🏦', 'Wealth and abundance.'),
  '荣': NameChar('荣', 'róng', ['Glory', 'Honor'], '木', '🌻', 'Glory and flourishing.'),
  '昌': NameChar('昌', 'chāng', ['Prosperous', 'Bright'], '火', '☀️', 'Prosperity.'),
  '春': NameChar('春', 'chūn', ['Spring', 'Vitality'], '木', '🌸', 'Spring and renewed life.'),
  '夏': NameChar('夏', 'xià', ['Summer', 'Vibrant'], '火', '☀️', 'Summer. Grand.'),
  '秋': NameChar('秋', 'qiū', ['Autumn', 'Harvest'], '金', '🍂', 'Autumn. Maturity.'),
  '冬': NameChar('冬', 'dōng', ['Winter', 'Serene'], '水', '❄️', 'Winter. Serene.'),
  '星': NameChar('星', 'xīng', ['Star', 'Bright'], '火', '⭐', 'Stars and brightness.'),
  '月': NameChar('月', 'yuè', ['Moon', 'Elegant'], '水', '🌙', 'The moon.'),
  '阳': NameChar('阳', 'yáng', ['Sun', 'Positive'], '火', '☀️', 'Sunlight.'),
  '光': NameChar('光', 'guāng', ['Light', 'Bright'], '火', '💡', 'Light and radiance.'),
  '德': NameChar('德', 'dé', ['Virtue', 'Integrity'], '火', '💎', 'Moral virtue.'),
  '仁': NameChar('仁', 'rén', ['Benevolent', 'Kind'], '水', '💕', 'Benevolence.'),
  '义': NameChar('义', 'yì', ['Righteous', 'Just'], '金', '⚔️', 'Righteousness.'),
  '礼': NameChar('礼', 'lǐ', ['Polite', 'Etiquette'], '火', '🎩', 'Politeness.'),
  '信': NameChar('信', 'xìn', ['Trust', 'Faithful'], '金', '🤝', 'Trustworthiness.'),
  '忠': NameChar('忠', 'zhōng', ['Loyal', 'Devoted'], '火', '🛡️', 'Loyalty.'),
  '孝': NameChar('孝', 'xiào', ['Filial', 'Respectful'], '水', '🙏', 'Filial piety.'),
  '良': NameChar('良', 'liáng', ['Good', 'Kind'], '金', '😇', 'Goodness.'),
  '善': NameChar('善', 'shàn', ['Kind', 'Good'], '金', '💝', 'Kindness.'),
  '诚': NameChar('诚', 'chéng', ['Sincere', 'Honest'], '金', '💛', 'Sincerity.'),
  '谦': NameChar('谦', 'qiān', ['Modest', 'Humble'], '木', '🎋', 'Modesty.'),
  '爱': NameChar('爱', 'ài', ['Love', 'Affection'], '火', '❤️', 'Love and affection.'),
  '心': NameChar('心', 'xīn', ['Heart', 'Soul'], '火', '💖', 'The heart.'),
  '欣': NameChar('欣', 'xīn', ['Joy', 'Happy'], '木', '😊', 'Joy and happiness.'),
  '乐': NameChar('乐', 'lè', ['Joy', 'Happiness'], '火', '🎵', 'Joy and music.'),
  '喜': NameChar('喜', 'xǐ', ['Joy', 'Delight'], '火', '😄', 'Happiness.'),
  '悦': NameChar('悦', 'yuè', ['Delighted', 'Happy'], '金', '😊', 'Delight.'),
  '怡': NameChar('怡', 'yí', ['Joyful', 'Harmonious'], '土', '😌', 'Joyful harmony.'),
  '梦': NameChar('梦', 'mèng', ['Dream', 'Aspiration'], '木', '🌙', 'Dreams.'),
  '成': NameChar('成', 'chéng', ['Achieve', 'Succeed'], '金', '🏆', 'Achievement.'),
  '功': NameChar('功', 'gōng', ['Merit', 'Achievement'], '木', '🏅', 'Merit.'),
  '立': NameChar('立', 'lì', ['Stand', 'Establish'], '火', '📐', 'Standing.'),
  '元': NameChar('元', 'yuán', ['First', 'Primary'], '木', '1️⃣', 'First and primary.'),
  '大': NameChar('大', 'dà', ['Big', 'Great'], '火', '🐘', 'Greatness.'),
  '中': NameChar('中', 'zhōng', ['Center', 'Balance'], '土', '🎯', 'Balance.'),
  '小': NameChar('小', 'xiǎo', ['Small', 'Delicate'], '金', '🌸', 'Small and delicate.'),
  '安': NameChar('安', 'ān', ['Peace', 'Safety'], '土', '🕊️', 'Peace.'),
  '宁': NameChar('宁', 'níng', ['Serene', 'Peaceful'], '火', '🧘', 'Serenity.'),
  '静': NameChar('静', 'jìng', ['Quiet', 'Calm'], '金', '🌙', 'Calmness.'),
  '和': NameChar('和', 'hé', ['Harmony', 'Peace'], '土', '☯️', 'Harmony.'),
  '平': NameChar('平', 'píng', ['Peaceful', 'Equal'], '水', '☮️', 'Peace.'),
  '顺': NameChar('顺', 'shùn', ['Smooth', 'Harmonious'], '金', '🌊', 'Smoothness.'),
  '永': NameChar('永', 'yǒng', ['Eternal', 'Forever'], '水', '♾️', 'Eternity.'),
  '方': NameChar('方', 'fāng', ['Square', 'Upright'], '土', '⬛', 'Upright.'),
  '正': NameChar('正', 'zhèng', ['Correct', 'Just'], '金', '✅', 'Correctness.'),
  '真': NameChar('真', 'zhēn', ['True', 'Genuine'], '水', '💫', 'Truth.'),
  '子': NameChar('子', 'zǐ', ['Child', 'Son'], '水', '👶', 'Child.'),
  '思': NameChar('思', 'sī', ['Thoughtful', 'Think'], '金', '💭', 'Deep thought.'),
  '学': NameChar('学', 'xué', ['Study', 'Learning'], '水', '📝', 'Pursuit of knowledge.'),
  '知': NameChar('知', 'zhī', ['Knowledge', 'Wise'], '火', '🎓', 'Knowledge.'),
  '智': NameChar('智', 'zhì', ['Wisdom', 'Intelligent'], '火', '🧠', 'Wisdom.'),
  '哲': NameChar('哲', 'zhé', ['Philosophical', 'Wise'], '火', '📚', 'Philosophy.'),
  '达': NameChar('达', 'dá', ['Achieve', 'Understand'], '火', '🎯', 'Achievement.'),
  '君': NameChar('君', 'jūn', ['Monarch', 'Gentleman'], '金', '👑', 'Monarch.'),
  '家': NameChar('家', 'jiā', ['Home', 'Family'], '火', '🏠', 'Home and family.'),
  '国': NameChar('国', 'guó', ['Country', 'Nation'], '火', '🏛️', 'Country.'),
  '鹏': NameChar('鹏', 'péng', ['Roc', 'Soaring'], '水', '🦅', 'Mythical roc bird.'),
  '飞': NameChar('飞', 'fēi', ['Fly', 'Soar'], '水', '🕊️', 'Flying.'),
  '翔': NameChar('翔', 'xiáng', ['Soar', 'Glide'], '水', '🦅', 'Soaring.'),
  '晨': NameChar('晨', 'chén', ['Morning', 'Dawn'], '火', '🌅', 'Morning.'),
  '曦': NameChar('曦', 'xī', ['Sunlight', 'Radiant'], '火', '☀️', 'Morning sunlight.'),
  '晓': NameChar('晓', 'xiǎo', ['Dawn', 'Know', 'Daybreak'], '火', '🌄', 'Dawn. Common in female names.'),
  '浩': NameChar('浩', 'hào', ['Vast', 'Expansive'], '水', '🌅', 'Vastness.'),
  '涛': NameChar('涛', 'tāo', ['Wave', 'Surge'], '水', '🌊', 'Great waves.'),
  '峰': NameChar('峰', 'fēng', ['Peak', 'Summit'], '山', '⛰️', 'Mountain peak.'),
  '岳': NameChar('岳', 'yuè', ['High Mountain'], '山', '🗻', 'Lofty mountain.'),
  '森': NameChar('森', 'sēn', ['Forest', 'Lush'], '木', '🌳', 'Dense forest.'),
  '松': NameChar('松', 'sōng', ['Pine', 'Resilient'], '木', '🌲', 'Pine tree.'),
  '梅': NameChar('梅', 'méi', ['Plum Blossom'], '木', '🌸', 'Plum blossom.'),
  '兰': NameChar('兰', 'lán', ['Orchid', 'Elegant'], '木', '🌷', 'Orchid.'),
  '竹': NameChar('竹', 'zhú', ['Bamboo', 'Flexible'], '木', '🎋', 'Bamboo.'),
  '荷': NameChar('荷', 'hé', ['Lotus', 'Pure'], '木', '🪷', 'Lotus.'),
  '莲': NameChar('莲', 'lián', ['Lotus', 'Sacred'], '木', '🪷', 'Sacred lotus.'),
  '雪': NameChar('雪', 'xuě', ['Snow', 'Pure'], '水', '❄️', 'Snow.'),
  '云': NameChar('云', 'yún', ['Cloud', 'Lofty'], '水', '☁️', 'Clouds.'),
  '霞': NameChar('霞', 'xiá', ['Rosy Clouds'], '水', '🌅', 'Rosy sunset clouds.'),
  '虹': NameChar('虹', 'hóng', ['Rainbow', 'Colorful'], '火', '🌈', 'Rainbow.'),
  '桃': NameChar('桃', 'táo', ['Peach', 'Longevity'], '木', '🍑', 'Peach.'),
  '桂': NameChar('桂', 'guì', ['Laurel', 'Fragrant'], '木', '🌼', 'Laurel.'),
  '芬': NameChar('芬', 'fēn', ['Fragrance', 'Scent'], '木', '🌸', 'Fragrance.'),
  '芳': NameChar('芳', 'fāng', ['Fragrant', 'Virtuous'], '木', '🌷', 'Fragrance.'),
  '花': NameChar('花', 'huā', ['Flower', 'Bloom'], '木', '🌸', 'Flowers.'),
  '剑': NameChar('剑', 'jiàn', ['Sword', 'Valiant'], '金', '⚔️', 'Sword.'),
  '军': NameChar('军', 'jūn', ['Army', 'Military'], '火', '🎖️', 'Army.'),
  '武': NameChar('武', 'wǔ', ['Martial', 'Valiant'], '火', '⚔️', 'Martial arts.'),
  '刚': NameChar('刚', 'gāng', ['Firm', 'Strong'], '金', '⛰️', 'Unyielding strength.'),
  '力': NameChar('力', 'lì', ['Power', 'Strength'], '火', '💥', 'Power itself.'),
  '豪': NameChar('豪', 'háo', ['Heroic', 'Bold'], '金', '🏅', 'Heroism.'),
  '宏': NameChar('宏', 'hóng', ['Grand', 'Vast'], '水', '🌊', 'Grandeur.'),
  '盛': NameChar('盛', 'shèng', ['Flourishing', 'Grand'], '火', '🔥', 'Thriving.'),
  '振': NameChar('振', 'zhèn', ['Energize', 'Inspire'], '金', '🚀', 'Revitalize.'),
  '建': NameChar('建', 'jiàn', ['Build', 'Establish'], '木', '🏗️', 'Building.'),
  '超': NameChar('超', 'chāo', ['Exceed', 'Surpass'], '金', '🚀', 'Exceeding.'),
  '开': NameChar('开', 'kāi', ['Open', 'Begin'], '木', '🔓', 'Opening.'),
  '新': NameChar('新', 'xīn', ['New', 'Fresh'], '金', '🌟', 'Newness.'),
  '先': NameChar('先', 'xiān', ['First', 'Pioneer'], '金', '🥇', 'Being first.'),
  '全': NameChar('全', 'quán', ['Complete', 'Perfect'], '火', '🎯', 'Completeness.'),
  '世': NameChar('世', 'shì', ['World', 'Generation'], '金', '🌍', 'World.'),
  '万': NameChar('万', 'wàn', ['Ten Thousand'], '火', '💯', 'Countless.'),
  '千': NameChar('千', 'qiān', ['Thousand'], '金', '💫', 'A thousand.'),
  '百': NameChar('百', 'bǎi', ['Hundred'], '火', '💯', 'Hundred.'),
  '长': NameChar('长', 'cháng', ['Long', 'Eternal'], '木', '📏', 'Longevity.'),
  '山': NameChar('山', 'shān', ['Mountain'], '山', '🏔️', 'Mountains.'),
  '石': NameChar('石', 'shí', ['Stone', 'Firm'], '山', '🪨', 'Stone.'),
  '江': NameChar('江', 'jiāng', ['River', 'Flow'], '水', '🏞️', 'Great rivers.'),
  '河': NameChar('河', 'hé', ['River'], '水', '🌊', 'Rivers.'),
  '源': NameChar('源', 'yuán', ['Source', 'Origin'], '水', '🌊', 'Water source.'),
  '泽': NameChar('泽', 'zé', ['Marsh', 'Grace'], '水', '💧', 'Marshes.'),
  '润': NameChar('润', 'rùn', ['Moist', 'Nourish'], '水', '💦', 'Moisture.'),
  '清': NameChar('清', 'qīng', ['Clear', 'Pure'], '水', '💎', 'Clear and pure.'),
  '冰': NameChar('冰', 'bīng', ['Ice', 'Pure'], '水', '❄️', 'Ice.'),
  '红': NameChar('红', 'hóng', ['Red', 'Vibrant'], '火', '🔴', 'Red.'),
  '绿': NameChar('绿', 'lǜ', ['Green', 'Fresh'], '木', '💚', 'Green.'),
  '蓝': NameChar('蓝', 'lán', ['Blue', 'Clear'], '木', '🔵', 'Blue.'),
  '紫': NameChar('紫', 'zǐ', ['Purple', 'Noble'], '火', '💜', 'Purple.'),
  '白': NameChar('白', 'bái', ['White', 'Pure'], '金', '⬜', 'White.'),
  '黑': NameChar('黑', 'hēi', ['Black', 'Dark'], '水', '⬛', 'Black.'),
  '柔': NameChar('柔', 'róu', ['Soft', 'Gentle'], '木', '🐑', 'Softness.'),
  '娇': NameChar('娇', 'jiāo', ['Tender', 'Lovely'], '火', '🌷', 'Tender loveliness.'),
  '媚': NameChar('媚', 'mèi', ['Charming', 'Alluring'], '水', '💋', 'Charm.'),
  '倩': NameChar('倩', 'qiàn', ['Pretty', 'Charming'], '火', '😊', 'Charming.'),
  '淑': NameChar('淑', 'shū', ['Gentle', 'Refined'], '水', '🤍', 'Gentle refinement.'),
  '娴': NameChar('娴', 'xián', ['Refined', 'Elegant'], '火', '🎀', 'Refined elegance.'),
  '艳': NameChar('艳', 'yàn', ['Gorgeous', 'Radiant'], '火', '🌺', 'Vibrant beauty.'),
  '凤': NameChar('凤', 'fèng', ['Phoenix', 'Noble'], '火', '🦚', 'Mythical phoenix.'),
  '燕': NameChar('燕', 'yàn', ['Swallow', 'Graceful'], '水', '🐦', 'Graceful bird.'),
};

const Map<String, List<String>> enNames = {
  '伟': ['Victor', 'Vincent', 'Magnus'],
  '强': ['Ethan', 'Gabriel', 'Andrew'],
  '明': ['Lucas', 'Luke', 'Clark'],
  '慧': ['Sophia', 'Sage', 'Hannah'],
  '琳': ['Jade', 'Gemma', 'Lynn'],
  '雅': ['Yvonne', 'Grace', 'Eva'],
  '婷': ['Tina', 'Tiana', 'Grace'],
  '志': ['William', 'Will', 'Wilfred'],
  '龙': ['Drake', 'Dragon', 'Lucius'],
  '美': ['Bella', 'Grace', 'Belle'],
  '丽': ['Lily', 'Leah', 'Lia'],
  '娜': ['Natalie', 'Naomi', 'Nina'],
  '杰': ['Jason', 'Jay', 'Jack'],
  '文': ['Winston', 'Owen', 'Dean'],
  '博': ['Noah', 'Boris', 'Edmund'],
  '睿': ['Rory', 'Raymond', 'Sage'],
  '英': ['Ethan', 'Evan', 'Harrison'],
  '勇': ['Leo', 'Gideon', 'Valiant'],
  '毅': ['Derek', 'Ethan', 'Martin'],
  '健': ['Ethan', 'Felix', 'Zachary'],
  '海': ['Dylan', 'Marvin', 'Morgan'],
  '天': ['Skyler', 'Celeste', 'Orion'],
  '秀': ['Sue', 'Sharon', 'Grace'],
  '瑞': ['Ray', 'Felix', 'Roy'],
  '祥': ['Felix', 'Ben', 'Benedict'],
  '福': ['Felix', 'Floyd', 'Ben'],
  '金': ['Goldie', 'Aurelius', 'Kim'],
  '玉': ['Jade', 'Pearl', 'Gemma'],
  '宝': ['Trevor', 'Pearl', 'Jasper'],
  '华': ['Henry', 'Flora', 'Spencer'],
  '富': ['Richard', 'Forrest', 'Midas'],
  '荣': ['Gloria', 'Roy', 'Reginald'],
  '昌': ['Charles', 'Chester', 'Chase'],
  '春': ['April', 'Spring', 'Vern'],
  '夏': ['Summer', 'August', 'Sunny'],
  '秋': ['Autumn', 'Harvest', 'Hazel'],
  '冬': ['Winter', 'Noel', 'Ivy'],
  '星': ['Stella', 'Star', 'Esther'],
  '月': ['Luna', 'Selene', 'Mona'],
  '阳': ['Sunny', 'Oriole', 'Saul'],
  '光': ['Lucas', 'Felix', 'Lucian'],
  '德': ['Derek', 'David', 'Ethan'],
  '仁': ['Rene', 'Ryan', 'Ben'],
  '义': ['Ethan', 'Justin', 'Ivan'],
  '信': ['Faith', 'Tristan', 'Conrad'],
  '忠': ['Truman', 'Constance', 'Noah'],
  '爱': ['David', 'Amore', 'Cara'],
  '心': ['Cordelia', 'David', 'Hart'],
  '欣': ['Joy', 'Felix', 'Noah'],
  '乐': ['Joy', 'Felix', 'Felicity'],
  '悦': ['Joy', 'Felix', 'Felicity'],
  '梦': ['Dream', 'Mona', 'Noah'],
  '成': ['Victor', 'Vincent', 'Charles'],
  '元': ['Primus', 'Orion', 'Aaron'],
  '大': ['Magnus', 'Max', 'Grant'],
  '中': ['Chance', 'Ethan', 'Oliver'],
  '安': ['Noah', 'Irene', 'Solace'],
  '宁': ['Noah', 'Irene', 'Serena'],
  '静': ['Serena', 'Noah', 'Irene'],
  '和': ['Irene', 'Olivia', 'Harvey'],
  '平': ['Noah', 'Irene', 'Oliver'],
  '永': ['Everett', 'Evan', 'Noah'],
  '正': ['Justin', 'Ethan', 'Walter'],
  '真': ['Tristan', 'True', 'Ernest'],
  '子': ['Sonny', 'Noah', 'Ethan'],
  '思': ['Noah', 'Theo', 'Thomas'],
  '学': ['Lorenzo', 'Noah', 'Edgar'],
  '知': ['Noah', 'Theo', 'Jasper'],
  '智': ['Sage', 'Solomon', 'Albert'],
  '哲': ['Sage', 'Solomon', 'Theo'],
  '达': ['David', 'Daniel', 'Dale'],
  '君': ['James', 'Julian', 'King'],
  '家': ['Homer', 'Noah', 'Ethan'],
  '国': ['George', 'Gregory', 'Chase'],
  '鹏': ['Peter', 'Pete', 'Flynn'],
  '飞': ['Flynn', 'Avi', 'Icarus'],
  '翔': ['Flynn', 'Icarus', 'Avi'],
  '晨': ['Dawn', 'Aurora', 'Matteo'],
  '曦': ['Aurora', 'Sunny', 'Cyrus'],
  '浩': ['Hugo', 'Harvey', 'Dylan'],
  '涛': ['Toby', 'Dylan', 'Marshall'],
  '峰': ['Parker', 'Monty', 'Everest'],
  '岳': ['Monty', 'Yale', 'Sierra'],
  '森': ['Forrest', 'Silas', 'Glen'],
  '松': ['Pine', 'Everett', 'Glen'],
  '梅': ['Mae', 'May', 'Margaret'],
  '兰': ['Orchid', 'Lily', 'Violet'],
  '竹': ['Bamboo', 'Benedict', 'Cole'],
  '荷': ['Lotus', 'Lily', 'Nel'],
  '莲': ['Lily', 'Lotus', 'Leah'],
  '雪': ['Snow', 'Nevada', 'Winter'],
  '云': ['Skye', 'Nimbus', 'Cloud'],
  '霞': ['Rose', 'Aurora', 'Skye'],
  '虹': ['Iris', 'Rainbow', 'Skye'],
  '桃': ['Peach', 'Georgia', 'Persica'],
  '桂': ['Laura', 'Laurel', 'Lawrence'],
  '芬': ['Fiona', 'Flora', 'Rose'],
  '芳': ['Fiona', 'Flora', 'Rose'],
  '花': ['Flora', 'Flower', 'Rose'],
  '剑': ['Marcus', 'Ethan', 'Blade'],
  '武': ['Marcus', 'Martin', 'Lewis'],
  '刚': ['Ethan', 'Gabriel', 'Stanley'],
  '力': ['Ethan', 'Gabriel', 'Conan'],
  '豪': ['Howard', 'Harvey', 'Hank'],
  '宏': ['Henry', 'Harold', 'Hugh'],
  '盛': ['Felix', 'Florence', 'Prosper'],
  '振': ['Victor', 'Vincent', 'Vince'],
  '建': ['Benedict', 'Dean', 'Mason'],
  '超': ['Charles', 'Chase', 'Super'],
  '开': ['Kai', 'Cole', 'Dean'],
  '新': ['Neo', 'Novak', 'Felix'],
  '全': ['Paul', 'Preston', 'Keegan'],
  '世': ['Mason', 'Desmond', 'Jeremy'],
  '长': ['Everett', 'Evan', 'Noah'],
  '高': ['Hayes', 'Alistair', 'Major'],
  '山': ['Monty', 'Rocky', 'Sierra'],
  '石': ['Stone', 'Rocky', 'Peter'],
  '江': ['River', 'Jordan', 'Brooks'],
  '河': ['River', 'Brooks', 'Jordan'],
  '源': ['Jordan', 'River', 'Wells'],
  '泽': ['Zachary', 'Marsh', 'Grace'],
  '润': ['Ryan', 'Rain', 'Dylan'],
  '清': ['Clive', 'Clark', 'Crystal'],
  '冰': ['Blake', 'Bianca', 'Crystal'],
  '红': ['Ruby', 'Scarlett', 'Rose'],
  '白': ['Blake', 'Albus', 'Bianca'],
  '柔': ['Noah', 'Ethan', 'Oliver'],
};

const Map<String, String> surnames = {
  '张': 'Zhang', '李': 'Li', '王': 'Wang', '赵': 'Zhao', '刘': 'Liu',
  '陈': 'Chen', '杨': 'Yang', '黄': 'Huang', '周': 'Zhou', '吴': 'Wu',
  '徐': 'Xu', '孙': 'Sun', '马': 'Ma', '朱': 'Zhu', '胡': 'Hu',
  '林': 'Lin', '高': 'Gao', '何': 'He', '郭': 'Guo', '罗': 'Luo',
  '梁': 'Liang', '宋': 'Song', '唐': 'Tang', '韩': 'Han', '曹': 'Cao',
  '许': 'Xu', '邓': 'Deng', '萧': 'Xiao', '冯': 'Feng', '程': 'Cheng',
  '蔡': 'Cai', '潘': 'Pan', '袁': 'Yuan', '叶': 'Ye', '蒋': 'Jiang',
  '沈': 'Shen', '任': 'Ren', '姚': 'Yao', '卢': 'Lu', '傅': 'Fu',
  '钟': 'Zhong', '崔': 'Cui', '汪': 'Wang', '陆': 'Lu', '戴': 'Dai',
  '范': 'Fan', '方': 'Fang', '石': 'Shi', '廖': 'Liao', '熊': 'Xiong',
  '金': 'Jin', '谭': 'Tan', '夏': 'Xia', '韦': 'Wei', '贾': 'Jia',
};
